### PR TITLE
fix: add missing typeof in delay check

### LINKED ISSUE #14: Delays result in fares not found
For the connection below, no fares are found.

This is caused by not taking into account the 60 seconds `arrivalDelay` in the [delay check](https://github.com/stadtnavi/fares-service/blob/36e03cd2f4d7cfe852b60b87c149b60dc477ee5d/lib/fetch-fares.js#L136). I'll provide a fix.

```json
{
    "duration": 1914,
    "endTime": 1742200829000,
    "legs": [
        {
            "arrivalDelay": 60,
            "departureDelay": 0,
            "distance": 21316.07,
            "dropOffBookingInfo": null,
            "duration": 900,
            "endTime": 1742200200000,
            "from": {
                "bikePark": null,
                "bikeRentalStation": null,
                "lat": 48.948746,
                "lon": 8.956868,
                "name": "Vaihingen (E) Gleis 7",
                "stop": {
                    "alerts": [],
                    "code": null,
                    "gtfsId": "1:de:08118:5879:1:7",
                    "platformCode": "Gleis 7",
                    "vehicleMode": "RAIL",
                    "zoneId": null
                },
                "vertexType": "TRANSIT"
            },
            "interlineWithPreviousLeg": false,
            "intermediatePlace": false,
            "mode": "RAIL",
            "realTime": true,
            "realtimeState": null,
            "rentedBike": null,
            "route": {
                "agency": {
                    "fareUrl": null,
                    "gtfsId": "1:ddb-GA",
                    "name": "Arverio Baden-Württemberg",
                    "phone": null
                },
                "alerts": [],
                "color": null,
                "desc": null,
                "gtfsId": "1:ddb-90-T01-1",
                "longName": null,
                "shortName": "RE 1",
                "type": 2,
                "url": null
            },
            "startTime": 1742199300000,
            "to": {
                "bikePark": null,
                "bikeRentalStation": null,
                "carPark": null,
                "lat": 48.89408,
                "lon": 8.70277,
                "name": "Pforzheim Hauptbahnhof",
                "stop": {
                    "alerts": [],
                    "code": null,
                    "gtfsId": "1:de:08231:50:3:4",
                    "name": "Pforzheim Hauptbahnhof",
                    "platformCode": null,
                    "vehicleMode": "RAIL",
                    "zoneId": null
                },
                "vertexType": "TRANSIT"
            },
            "transitLeg": true,
            "trip": {
                "gtfsId": "1:ddb-90-T01-1-1-131-R-5-Special#1448-305-502",
                "pattern": {
                    "code": "1:ddb-90-T01-1:1:82"
                },
                "tripHeadsign": "Karlsruhe Hauptbahnhof"
            }
        }
    ],
    "startTime": 1742198915000,
    "walkDistance": 1120.1
}
```

### PR DESCRIPTION
**Pull request by hbruch**
This PR adds a missing `typeof` in the the delay existance check.

Fixes #14.

### CODE REVIEW

File: lib/fetch-fares.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ const triasJourneyMatchesOtpItinerary = (logger, it) => (j) => {
 		return false
 	}
 	let itDep = +new Date(itLeg0.startTime)
-	if ('number' === itLeg0.departureDelay) itDep -= itLeg0.departureDelay * 1000 // todo: seconds?
+	if ('number' === typeof itLeg0.departureDelay) itDep -= itLeg0.departureDelay * 1000 // todo: seconds?
```
Comment (derhuerst) [inline lib/fetch-fares.js:115]: Good catch!

If you're changing this anyways: `Number.isInteger()` or `Number.isFinite()` are more precise than using `typeof`.

Also, the "todo: seconds?" comment can be removed I'd say.

**Review by derhuerst — APPROVED** [review]
